### ISSUE TITLE
introduce an edit mode

### ISSUE THREAD

**Issue by dvdanielamoitzi** [ffg-seva/visahoi#119]
As a data journalist, I want to be able to easily edit onboarding messages in the UI.

**TODO**
- [x] provide two functions called "enterEditMode" and "exitEditMode" which the developer that integrates the library can call like "onboardingUI.enterEditMode()" (just like the removeOnboarding function)
- [x] create a store variable called "isEditModeActive"; default value: false
- [x] when the user calls "onboardingUI.enterEditMode()" the store variable "isEditModeActive" is set to true
- [x] when the store value is set to true, show a trash bin icon in every tooltip header ( to the left of the x (close) icon)
- [x] the icon does not have any functionality yet, we'll do that in another ticket
- [x] when the user calls "exitEditMode" the store value "isEditModeActive" should be set to false and the trash bin icons should be hidden again
